# appveyor.yml
version: 1.0.0.{build}

platform: x64

branches:
  only:
    - ci

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOVERSION: 1.16

install:
  # Install the specific Go version. See https://help.appveyor.com/discussions/problems/1215-go-14-support
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -oC:\ >nul
  - go version
  - go env

build_script:
  - cmd: .\build.bat

artifacts:
  - path: dist
    name: binary

deploy:
  provider: GitHub
  description: "This is a new release."
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: pPqb6qGq+cpAyYS/WRlmbJHVIptBixRQiglKWwLtBnaMZdmIZzc1J9MEvzEJsihc
  artifact: binary # This is the name we specified in the artifacts section.
  on: 
    branch: ci        # release from cn branch only
    APPVEYOR_REPO_TAG: true       # deploy on tag push only
